export const feedbacks = [
    {
        id: 1,
        name: "Sarah Mitchell",
        photo: "/images/feedback/profile-sarah.png",
        city: "USA, Colorado",
        heading: "Exceptional Service!",
        text: "Estatein went above and beyond to help us find the perfect home. Their team's dedication and expertise made a big difference in our search. We are incredibly grateful for their outstanding service!",
    },
    {
        id: 2,
        heading: "Outstanding Support",
        name: "Wade Warren",
        photo: "/images/feedback/profile-wade.png",
        city: "USA, California",
        text: "Our experience with Estatein was outstanding. Their team's dedication and professionalism made finding our dream home a breeze. Highly recommended!",
    },
    {
        id: 3,
        heading : "Exceptional Service!",
        name: "John Mans",
        photo: "/images/feedback/profile-john.png",
        city: "USA, Nevada",
        text: "Estatein exceeded my expectations. The property was stunning, and the staff was friendly and professional. ",
    },
    {
        id: 4,
        heading : "Professional and Friendly",
        name: "David Peterson",
        photo: "/images/feedback/profile-david.png",
        city: "USA, Texas",
        text: "Working with Estatein was a pleasure from start to finish. Their team  provided clear communication and exceptional support throughout the home-buying process. We felt well taken care of every step of the way!",
    },
    {
        id: 5,
        heading : "Efficient and Reliable",
        name: "Emelie Thomson",
        photo: "/images/feedback/profile-emelie.png",
        city: "USA, Florida",
        text: "Estatein provided us with top-notch service. They helped us sell our property quickly and at a great price. We couldn't be happier with the results.",
    },
    {
        id: 5,
        heading : "Smooth Transaction",
        name: "Mark Robinson",
        photo: "/images/feedback/profile-mark.png",
        city: "USA, New York",
        text: "Estatein made our real estate experience smooth and stress-free. They handled everything with great care and attention to detail. I would definitely recommend them to anyone looking to buy or sell property...",
    }
]